.github/workflows/ci.yml

Add codeclimate coverage report

---

README.md
cmd/unleash.go
coverage/coverage.go
coverage/coverage_test.go
mutator/mutator.go
mutator/mutator_test.go

Add support for build tags (#10)

---

.github/workflows/release.yml
.goreleaser.yaml
CONTRIBUTING.md

Prepare for GitLab Flow

---

cmd/gremlins/main.go
cmd/unleash.go

Fix call on path (#36)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Improve templates

---

.deepsource.toml
README.md
coverage/coverage_test.go
mutator/internal/tokenmutant.go
mutator/mutator.go
mutator/mutator_test.go
report/report_test.go

Add DeepSource integration and fix some of the findings.

Deep source integration

---

cmd/gremlins/main.go
log/log.go
log/log_test.go
report/report_test.go

Now error logs correctly go to STDERR.

Make error logs go to STDERR (#44)

---

.goreleaser.yaml
AUTHORS
README.md

Some chores before first release.

Prepare for first release

---

.deepsource.toml
.github/workflows/ci.yml
.goreleaser.yaml
README.md
cmd/gremlins.go
cmd/gremlins/main.go
cmd/unleash.go
coverage/coverage.go
coverage/coverage_test.go
coverage/profile_test.go
go.mod
log/log_test.go
mutant/mutant_test.go
mutator/internal/mappings.go
mutator/internal/node_test.go
mutator/internal/tokenmutant.go
mutator/internal/tokenmutant_test.go
mutator/mutator.go
mutator/mutator_test.go
mutator/workdir/workdir.go
mutator/workdir/workdir_test.go
report/report.go
report/report_test.go

Migrated the repository to go-gremlins organisation.

chores: migrate to go-gremlins organization

---

.golangci.yml
cmd/unleash.go
pkg/coverage/coverage.go
pkg/coverage/coverage_test.go
pkg/coverage/profile.go
pkg/coverage/profile_test.go
pkg/mutator/internal/node.go
pkg/mutator/internal/tokenmutant.go
pkg/mutator/internal/tokenmutant_test.go
pkg/mutator/mutator.go
pkg/mutator/mutator_test.go
pkg/mutator/workdir/workdir.go
pkg/mutator/workdir/workdir_test.go
pkg/report/report.go

Add more linters and fix relative issues. There are still
more linters that could be beneficial though.

add more linters

---

CODE_OF_CONDUCT.md

Changed the project email address.

docs: update project email

---

CODE_OF_CONDUCT.md

docs: update email address

---

.github/dependabot.yml

Add custom label

---

cmd/unleash.go

Small fix of the `-` in flags.

fix: point to flag dash

---

docs/docs/index.md
docs/docs/usage/commands/gremlins.md
docs/docs/usage/commands/unleash.md
docs/docs/usage/mutations/arithmetic_base.md
docs/docs/usage/mutations/conditionals_boundary.md
docs/docs/usage/mutations/conditionals_negation.md
docs/docs/usage/mutations/increment_decrement.md
docs/docs/usage/mutations/invert_negatives.md
docs/mkdocs.yml

Completed the basic documentation site.

docs: complete basic documentation

---

docs/docs/usage/mutations/conditionals_boundary.md
docs/docs/usage/mutations/conditionals_negation.md
docs/docs/usage/mutations/increment_decrement.md
docs/docs/usage/mutations/invert_negatives.md

Fix an extended markdown formatting error.

docs: fix formatting error

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
README.md
docs/CONTRIBUTING.md
docs/docs/CONTRIBUTING.md
docs/docs/index.md
docs/docs/install.md
docs/docs/usage/commands/index.md
docs/docs/usage/mutations/index.md
docs/mkdocs.yml

General updates to documentation, aka, add contributing and make dynamic package version in the guide.

docs: move contributing

---

.github/workflows/docs.yml
docs/docs/install.md
docs/docs/schema/configuration.json
docs/docs/usage/configuration.md
docs/mkdocs.yml

Add the JSON schema for the configuration file.

docs: add JSON schema

---

.github/workflows/ci.yml
Makefile
cmd/unleash.go
configuration/configuration.go
go.mod
go.sum
pkg/mutant/mutant.go
pkg/mutant/mutant_test.go
pkg/mutator/internal/tokenmutant_test.go
pkg/mutator/mutator_test.go

Also fix some deprecations of ioutil package.

global: update to go1.19

---

Makefile
configuration/configuration_test.go
internal/execution/execution_test.go
pkg/coverage/profile_test.go
pkg/mutant/mutant_test.go
pkg/mutator/internal/node_test.go
pkg/mutator/internal/tokenmutant.go
pkg/mutator/mutator.go
pkg/mutator/mutator_test.go
pkg/report/report_test.go

Properly aligned struct fields can reduce memory usage.

global: align struct fields

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release.yml
.goreleaser.yaml
Dockerfile
README.md
docs/docs/install.md
pkg/mutator/workdir/workdir.go
pkg/mutator/workdir/workdir_test.go

In this PR i have:
- Added a docker image.
- Made gremlins able to work within docker container.
- Made goreleaser able to build the docker image and make it available for download on docker hub.

docker: create docker image (#69)

---

.goreleaser.yaml

Make releaser use gomod proxy.

release: make build reproducible

---

.github/workflows/gremlins.yml

ci: add a gremlins step

---

.goreleaser.yaml

Also update the website with the new domain.

docker: add arm64 to Docker release

---

configuration/configuration.go
configuration/configuration_test.go

The config file loading order was inverted.

fix: config loading order

---

.github/workflows/ci.yml
.github/workflows/gremlins.yml

Also, put back the golangci-lint action.

ci: add gremlins action step

---

README.md

Update README to use shields.io where possible.

docs: use shields.io where possible

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/release.yml
.github/workflows/ci.yml
.github/workflows/gremlins.yml

Some maintenance chores on CI and issue templates.

chore: maintain CI and templates

---

internal/engine/executor.go
internal/engine/executor_test.go
internal/engine/stubs_test.go
internal/engine/tokenmutator.go
internal/engine/workerpool/workerpool_test.go
internal/mutator/mutator.go
internal/report/report_test.go

Fixes #170 
I do not know if we can/want add some kind of regression test, wdyt?

bug: fix unreliable results when using multiple workers

---

docs/docs/usage/commands/unleash/index.md

docs: fix documentation formatting
