- cmd/unleash.go
When unleash is called without a path, it should
operate on the current directory.
> Fix missing path (#36)

- .deepsource.toml
- README.md
- mutant/mutant.go
- mutant/mutant_test.go
- mutator/mutator.go
- mutator/mutator_test.go
- report/report.go
- report/report_test.go
I implemented the timeout using the context with timeout, and the with context version of exec.Command.
I also changed the name BUILD FAILED into NOT VIABLE which is more generic and can apply to more cases in the future.
> Add TIMED OUT and NOT VIABLE (#40)

- AUTHORS
If Google can remove it, we can as well. Git commits are
enough to attribute copyright.
> remove authors file

- pkg/mutator/mutator.go
> fix: process resources are not released

- .gremlins.yaml
- cmd/gremlins.go
- cmd/gremlins_test.go
- cmd/internal/flags/flags.go
- cmd/internal/flags/flags_test.go
- cmd/unleash.go
- cmd/unleash_test.go
- configuration/configuration.go
- configuration/configuration_test.go
- configuration/mutantenabled.go
- configuration/mutantenables_test.go
- pkg/mutant/mutant.go
- pkg/mutator/mutator.go
- pkg/mutator/mutator_test.go
- pkg/mutator/testdata/fixtures/0_all_go
In this PR I have:
- implemented a dynamic flag/configKey generation for all supported mutant types
- added a table of default enablement for all supported `mutant.Type`
- currently the flag format is: `m-<mutant-type> bool` and the config key is `mutants.<mutant-type>.enabled`
- `--arithmetic-base`
- `--conditionals-boundary`
- `--conditionals-negation`
- `--increment-decrement`
- `--invert-negatives`
The configuration file now supports:
```yaml
mutants:
aritmetic-base:
enabled: true
conditionals-boundary:
enabled: true
conditionals-negation:
enabled: true
increment-decrement:
enabled: true
invert-negatives:
enabled: true
```
> feat: make mutant types switchable

- .github/workflows/ci.yml
- cmd/internal/flags/flags.go
- cmd/internal/flags/flags_test.go
- cmd/unleash.go
- pkg/coverage/coverage.go
- pkg/log/log.go
Parameters over 80 bytes should be passed as pointers rather then by
copy. 
Also, update golangci-lint to work with go1.19.
> coverage: optimize heavy lifting of parameters

- cmd/gremlins.go
- cmd/gremlins_test.go
- cmd/internal/flags/flags.go
- cmd/internal/flags/flags_test.go
- configuration/configuration.go
- docs/docs/usage/commands/index.md
- docs/docs/usage/configuration.md
- pkg/log/log.go
- pkg/log/log_test.go
In this PR I added a _silent_ mode. It can be enabled via `--silent`/`-s`. In this mode, gremlins will be completely silent and just report errors if they happen.
> log: add silent mode

- cmd/unleash.go
- cmd/unleash_test.go
- configuration/configuration.go
- docs/docs/schema/configuration.json
- docs/docs/usage/commands/unleash.md
- docs/docs/usage/configuration.md
- pkg/coverage/coverage.go
- pkg/coverage/coverage_test.go
- pkg/mutator/mutator.go
- pkg/mutator/mutator_test.go
- pkg/report/internal/structure.go
- pkg/report/report.go
- pkg/report/report_test.go
- pkg/report/testdata/normal_output.json
In this PR I
- added a `--output`/`-o` flag to `unleash`
- if set, it will print a JSON file with all the results
- updated the documentation accordingly
If the output file is not writeable, gremlins will log the fact, but will not exit with an error.
> report: add JSON output to file

- README.md
- docs/docs/index.md
The README file should report only concise information that doesn't
change much among releases. For the complete documentation there is
the documentation website.
> docs: reduce README to essential information

- pkg/report/report.go
- pkg/report/report_test.go
After the generification of Viper get, if a numerical value was
stored without making it an explicit float, when retrieved
as float64 it was always 0.
> report: fix get as float if stored as int

- docs/docs/install.md
`go install` argument cannot contain protocol
> docs: fix source install instruction

- pkg/mutator/mutator.go
- pkg/mutator/mutator_test.go
There was a resource leakage since we the external management of timeout. Gremlins killed the test process, but not the child processes that remained hanging forever.
> mutator: fix resource leakage

- pkg/coverage/coverage.go
- pkg/mutator/mutator.go
Now, if the coverage run fails, it will print the combined output of the command instead of a cryptic "exit code 1".
> coverage: print combined output in case of failure

- configuration/mutantenabled.go
- configuration/mutantenables_test.go
- docs/docs/usage/commands/unleash/index.md
- docs/docs/usage/configuration.md
- docs/docs/usage/mutations/index.md
- docs/docs/usage/mutations/invert_logical.md
- docs/mkdocs.yml
- pkg/mutant/mutant.go
- pkg/mutant/mutant_test.go
- pkg/mutator/internal/mappings.go
- pkg/mutator/mutator_test.go
- pkg/mutator/testdata/fixtures/land_go
- pkg/mutator/testdata/fixtures/lor_go
Closes #137 
A new mutator replaces && with || and vice versa.
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._
> Add invert logical operations mutator

- cmd/unleash.go
- cmd/unleash_test.go
- pkg/mutant/mutant.go
- pkg/mutator/mutator_test.go
- pkg/mutator/stubs_test.go
Exported names should not start with the package name, in this case
mutant.MutantTypes should be mutant.Types, and that's exactly
what I did here.
> mutant: refactor to respect Go convention

- configuration/mutantenables_test.go
This should prevent the behaviour described in #142, where a new mutant
can be added with a default status which is not explicitly tested.
Now TestMutantDefaultStatus checks if all the registered mutants
are tested for their default status.
Closes #142
> config: prevent mutants not tested for default

- .golangci.yml
Remove the snake-case linter which is deprecated and add the suggested
configuration for Revive.
> ci: update golangci-lint

- docs/docs/schema/configuration.json
- docs/docs/usage/commands/unleash/index.md
- docs/docs/usage/configuration.md
- docs/docs/usage/mutations/index.md
- docs/docs/usage/mutations/invert_loop.md
- docs/mkdocs.yml
- internal/configuration/mutantenabled.go
- internal/configuration/mutantenables_test.go
- internal/engine/engine_test.go
- internal/engine/mappings.go
- internal/engine/node.go
- internal/engine/node_test.go
- internal/engine/testdata/fixtures/loop_break_go
- internal/engine/testdata/fixtures/loop_continue_go
- internal/mutator/mutator.go
- internal/mutator/mutator_test.go
Implement #136 invert loop break/continue
I've added the loop control support. I'm not sure if the fixtures are good enough.
I was wondering what will happen when changing the control results in an infinite loop?
> mutant: add INVERT_LOOPCTRL mutation

- internal/engine/tokenmutator.go
- internal/engine/workdir/testdata/filetocopy_go
- internal/engine/workdir/workdir.go
- internal/engine/workdir/workdir_test.go
In this pr i have:
- Replaced the hard link by the copy of the files.
- Removed the elimination of the file within tokenmutator.Apply method since now the files are full copies of the original ones.
- Added a Benchmark Test for Dealer.Get method to use as a starting point for further enhancements.
> Replace hardlinks with a copy of the files

- cmd/unleash.go
- cmd/unleash_test.go
- docs/docs/schema/configuration.json
- docs/docs/usage/commands/unleash/index.md
- internal/configuration/configuration.go
- internal/coverage/coverage.go
- internal/coverage/coverage_test.go
A flag --coverpkg is added to the unleash command. This is handed over to the call of "go test -cover", similar to flag --tags.
Resolves #162
> coverage: add support for flag --coverpkg

- internal/engine/executor.go
- internal/engine/executor_test.go
- internal/engine/stubs_test.go
- internal/engine/workdir/workdir.go
- internal/engine/workdir/workdir_test.go
Closes #182. 
The proposed PR is an idea to overcome the issue of not cleaning build folders when going into time out.
Writing the test it felt a bit awkward the way I got the root dir of our `wdDealer`. I think in writing this line: 
```go
goTmpDirEnv := fmt.Sprintf("GOTMPDIR=%s", filepath.Dir(mut.Workdir()))
```
I'm leaking implementation logic in our test.
So I was thinking of another way to get the same result in a cleaner way. We might add a new func in the `Dealer interface`  that returns the root working directory.
```go
type Dealer interface {
Get(idf string) (string, error)
WorkDir() string
Clean()
}
```
Introduction the `WorkDir()` getter we can also refactor the implementation in just this 2 lines:
```go
cmd.Env = append(cmd.Env, os.Environ()...)
cmd.Env = append(cmd.Env, …
```
> Use GOTMPDIR env to clean all the go-build folders

- cmd/internal/flags/flags_test.go
- cmd/unleash.go
- cmd/unleash_test.go
- docs/docs/index.md
- docs/docs/usage/ci/github-action.md
- docs/docs/usage/commands/unleash/index.md
- go.mod
- go.sum
- internal/configuration/configuration.go
- internal/diff/diff.go
- internal/diff/diff_test.go
- internal/diff/parse.go
- internal/diff/parse_test.go
- internal/engine/engine.go
- internal/engine/engine_test.go
- internal/engine/executor.go
- internal/mutator/mutator.go
- internal/report/report.go
- internal/report/report_test.go
Running mutations only for changes. A new flag `diff` runs `git diff` with reference and skip mutants outside of changes.
```
Killed: 16, Lived: 0, Not covered: 1
Timed out: 0, Not viable: 0, Skipped: 168
Test efficacy: 100.00%
Mutator coverage: 94.12%
```
Look at [docs change](https://github.com/go-gremlins/gremlins/pull/215/files#diff-c3b11fad1e53f8f988a321e5e9621308c6bbf83cb4f67d19888a1fd987f73ba2R63) for details.
> feat: add only diff run flag
